spring:
  profiles:
    active: default
  application:
    name: ms-users
  datasource:
    url: jdbc:postgresql://${DB_DOMAIN:DB_DOMAIN_LOCAL}:5432/financial_services_db # local
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none # <create | create-drop | update | validate | none>
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ms_users
    show-sql: true
  sql:
    init:
      mode: always
springdoc:
  api-docs:
    path: /api-docs
logging:
  level:
    root: info
ms-users:
  clients:
    # noinspection SpringBootApplicationYaml
    ms-transactions: ${MS_TRANSACTION_DOMAIN:localhost}:${MS_TRANSACTION_PORT:8081}
server:
  port: ${MS_USER_PORT:8080}